# Site settings
title: "Malvika Tejura, Ph.D. - Resume"
description: "Resume for Dr. Malvika Tejura"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Malvika Tejura, Ph.D."
resume_title:                   "PhD in Genome Sciences, University of Washington"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "malvika.tejura20@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "address • phone • email"
display_header_contact_info:    "false"

resume_header_intro: "<p>I work at the intersection of biology and machine learning, especially in the places where AI begins to break down in real biological systems. I’m a genomics researcher and published scientist who recently completed my PhD at the University of Washington. What makes my background somewhat unusual is that I started at the bench. Before moving fully into computation, I spent years in both academia and industry working with CRISPR/Cas9 systems in iPSCs and other cell models, and helping introduce new techniques for fluorescence imaging and functional assays at sequencing and therapeutics companies. During my PhD, I transitioned into a fully computational role, but that wet lab foundation continues to shape how I think about data: not as something abstract, but as something generated through messy, imperfect biological systems. As part of the NHGRI IGVF Consortium, I helped coordinate research across 15+ labs and created a framework that uses machine learning models with large-scale functional datasets to build a framework that ultimately shapes how clinicians interpret genetic variants in cancer, rare disease, and beyond. My work has centered on model evaluation, large-scale data integration, and reproducible analytical pipelines, while also translating complex findings for audiences ranging from bench scientists to clinical researchers. I’m looking for AI/ML and data science roles in healthcare and life sciences where I can help identify meaningful gaps and use AI to solve them in ways that are scientifically grounded, and uncover new insights from complex biological data. Open to roles in: ML evaluation, AI in healthcare, solutions engineering, biological AI safety, data science</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:        true
resume_section_education:         true
resume_section_publications:      true
resume_section_presentations:     true
resume_section_formal_teaching:   true
resume_section_informal_teaching: true
resume_section_mentoring:         true
resume_section_volunteering:      true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:             true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mtejura"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/malvika-tejura-9a2466133"
  # resume_instagram_url:         ""
  # resume_website_url:           ""
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
